### ISSUE TITLE
YAML Fields

### ISSUE THREAD

**Issue by benskutnik** [thefallingduck/RmdSyllabus#1]
This template was a huge time-saver for me. I am wondering how to edit the YAML to remove the "labroom" and "labhours" fields. I thought it would be as easy as deleting them out of the YAML but it's not working.

**Comment by thefallingduck** [comment]
Updated so the tex template contains an if statement to drop the labroom/labhours if missing.

`$if(labroom)$` is the main operator. Test it and let me know if it is fixed for you.

**Comment by benskutnik** [comment]
Works perfectly!
